eureka.client.serviceUrl.defaultZone=http://eureka:password@discovery-service:8761/eureka
spring.security.oauth2.resourceserver.jwt.issuer-uri= http://keycloak-service:8080/realms/spring-boot-microservices-realm
server.port=8081

##discovery service routes
spring.cloud.gateway.routes[0].id=discovery-service
spring.cloud.gateway.routes[0].uri=http://discovery-service:8761
spring.cloud.gateway.routes[0].predicates=Path=/eureka/web
spring.cloud.gateway.routes[0].filters[0]=SetPath=/