apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-product-deployment
  labels:
    app: mongo-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-product
  template:
    metadata:
      labels:
        app: mongo-product
    spec:
      containers:
      - name: mongo-product
        image: mongo:4.4.14-rc0-focal
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-product-service
spec:
  selector:
    app: mongo-product
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
