apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: mrunal02/product-service:latest
          ports:
            - containerPort: 8084
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-product-configmap
                  key: mongo-url
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: NodePort
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 30100
