apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: mrunal02/inventory-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-inventory-configmap
                  key: mysql-url
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-inventory-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-inventory-secret
                  key: mysql-password
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: NodePort
  selector:
    app: inventory-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30102
